begin;

create table if not exists public.telemetry_events_raw (
  id bigint generated by default as identity primary key,
  event_name text not null check (
    event_name in (
      'search',
      'search_empty',
      'select_origin',
      'prompt_shown',
      'prompt_answered',
      'results_rendered',
      'card_expanded',
      'abandon'
    )
  ),
  event_day date not null default current_date,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists telemetry_events_raw_day_event_idx
  on public.telemetry_events_raw (event_day, event_name);

create table if not exists public.telemetry_daily (
  event_day date not null,
  event_name text not null,
  dimension_key text not null,
  dimension_value text not null,
  event_count integer not null check (event_count >= 0),
  refreshed_at timestamptz not null default now(),
  primary key (event_day, event_name, dimension_key, dimension_value)
);

alter table public.telemetry_events_raw enable row level security;
alter table public.telemetry_daily enable row level security;
revoke all on public.telemetry_events_raw from anon, authenticated;
revoke all on public.telemetry_daily from anon, authenticated;
grant all on public.telemetry_events_raw to service_role;
grant all on public.telemetry_daily to service_role;

create or replace function public.refresh_telemetry_aggregates()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.telemetry_daily (
    event_day,
    event_name,
    dimension_key,
    dimension_value,
    event_count,
    refreshed_at
  )
  select
    event_day,
    event_name,
    'all',
    'all',
    count(*)::integer,
    now()
  from public.telemetry_events_raw
  where event_day = current_date
  group by event_day, event_name
  on conflict (event_day, event_name, dimension_key, dimension_value)
  do update set
    event_count = excluded.event_count,
    refreshed_at = now();

  insert into public.telemetry_daily (
    event_day,
    event_name,
    dimension_key,
    dimension_value,
    event_count,
    refreshed_at
  )
  select
    event_day,
    event_name,
    case
      when event_name in ('search', 'search_empty') then 'term'
      when event_name in ('prompt_shown', 'prompt_answered') then 'prompt'
      when event_name = 'select_origin' then 'food'
      when event_name = 'card_expanded' then 'block'
      else 'shape'
    end,
    case
      when event_name in ('search', 'search_empty') then payload->>'term'
      when event_name in ('prompt_shown', 'prompt_answered')
        then concat_ws(':', payload->>'prompt_id', payload->>'option_id')
      when event_name = 'select_origin' then payload->>'food_id'
      when event_name = 'card_expanded' then payload->>'block'
      when event_name = 'results_rendered'
        then concat_ws(':', payload->>'direct_count', payload->>'family_count', payload->>'prepared_count')
      else 'all'
    end,
    count(*)::integer,
    now()
  from public.telemetry_events_raw
  where event_day = current_date
  group by 1, 2, 3, 4
  having count(*) >= 5
  on conflict (event_day, event_name, dimension_key, dimension_value)
  do update set
    event_count = excluded.event_count,
    refreshed_at = now();

  delete from public.telemetry_events_raw
  where created_at < now() - interval '24 hours';

  delete from public.telemetry_daily
  where event_day < current_date - 90;
end;
$$;

revoke all on function public.refresh_telemetry_aggregates()
  from public, anon, authenticated;
grant execute on function public.refresh_telemetry_aggregates()
  to service_role;

commit;
