begin;

create table if not exists public.auth_rate_limits (
  key_hash text not null,
  scope text not null,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  primary key (key_hash, scope)
);

alter table public.auth_rate_limits enable row level security;
revoke all on public.auth_rate_limits from anon, authenticated;
grant all on public.auth_rate_limits to service_role;

create or replace function public.consume_auth_rate_limit(
  p_key text,
  p_scope text,
  p_window_seconds integer,
  p_max_attempts integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  insert into public.auth_rate_limits (
    key_hash,
    scope,
    attempt_count,
    expires_at,
    updated_at
  )
  values (
    p_key,
    p_scope,
    1,
    now() + make_interval(secs => p_window_seconds),
    now()
  )
  on conflict (key_hash, scope) do update
  set
    attempt_count = case
      when public.auth_rate_limits.expires_at <= now() then 1
      else public.auth_rate_limits.attempt_count + 1
    end,
    expires_at = case
      when public.auth_rate_limits.expires_at <= now()
        then now() + make_interval(secs => p_window_seconds)
      else public.auth_rate_limits.expires_at
    end,
    updated_at = now()
  returning attempt_count into next_count;

  delete from public.auth_rate_limits
  where expires_at < now() - interval '1 day';

  return next_count > p_max_attempts;
end;
$$;

revoke all on function public.consume_auth_rate_limit(text, text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_auth_rate_limit(text, text, integer, integer)
  to service_role;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null,
  admin_email text not null,
  action text not null check (
    action in (
      'member_created',
      'member_updated',
      'member_deactivated',
      'member_reactivated'
    )
  ),
  target_email text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_target_email_idx
  on public.admin_audit_log (target_email);

alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon, authenticated;
grant all on public.admin_audit_log to service_role;

alter table if exists public.users enable row level security;
revoke all on table public.users from anon, authenticated;
grant all on table public.users to service_role;

commit;
